server.port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloud-challenge/codex-config-files

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: file://home/spring/codex-config
