server.port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloud-challenge/codex-config-files

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: file://home/spring/codex-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


---
spring:
  profiles: kubernetes

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/