server.port: 8888

spring:
  application:
    name: codex-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloud-challenge/codex-config-files


  boot:
    admin:
      client:
        url: http://admin-server:8079

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8080/eureka/