server.port: 8888

spring:
  application:
    name: codex-config


  boot:
    admin:
      client:
        url: http://admin-server:8079

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8080/eureka/